// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTHquDSoIQaBqAvvBSLq95OgVDeZ1JPlk',
    appId: '1:44786388945:web:53aeda23828cd43cf05af0',
    messagingSenderId: '44786388945',
    projectId: 'whatsapp-messeneger-8bca4',
    authDomain: 'whatsapp-messeneger-8bca4.firebaseapp.com',
    storageBucket: 'whatsapp-messeneger-8bca4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4tcvwILI28XklpBvFYuJ7MWDRbMCOadI',
    appId: '1:44786388945:android:78ab7ff5c06a3bd9f05af0',
    messagingSenderId: '44786388945',
    projectId: 'whatsapp-messeneger-8bca4',
    storageBucket: 'whatsapp-messeneger-8bca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe5co5r2668I02u9sIjbgpcx0pWPAJ6_I',
    appId: '1:44786388945:ios:89dbe2a642ae93a3f05af0',
    messagingSenderId: '44786388945',
    projectId: 'whatsapp-messeneger-8bca4',
    storageBucket: 'whatsapp-messeneger-8bca4.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
